### ISSUE TITLE
some images not appearing in diagrammeR blogpost

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/sesync-ci.github.io#91]
In [the diagrammeR blogpost](https://cyberhelp.sesync.org/blog/visualization-with-diagrammeR.html) the last two images are blank. We should fix 'cuz that's one of our pages with the most views! 😄 @reblake

**Comment by reblake** [comment]
So I'm not sure why the mermaid-created images (last two images) disappeared initially.  When trying to fix it, I noticed that all images disappeared, because when the md was rendered from the Rmd, the images were no longer included inline as html, but rather a link to a PNG image was inserted into the md.  However, the site couldn't find that because it wasn't in the assets.  
The solution I implemented was to manually move the newly-created folder with the auto-generated PNG images to the correct location in `/assets/images/`, and manually edit the paths in the md file.  A workable solution, but still don't know what changed and why the rendering is different.
